version: '3.9'
services:
  flask:
    build: ./
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
      - DATABASE_URL=postgresql://postgre:password@host.docker.internal/db_for_proj  # !!! FOR START WITH docker-compose up
      #- DATABASE_URL=postgresql://postgre:password@localhost/db_for_proj  # @@@ FOR DEBUG IN PYCHARM
    volumes:
      - .F:\PyCharmCommunityEdition2020.2.2\FlaskPostgreDocker
    ports:
      - "5000:5000"
    expose:
      - 5000
    depends_on:
      - db
    restart: on-failure
    command: python run.py

  db:
    image: postgres
    restart: always
    # command: postgres -p 5432 # POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=db_for_proj
    environment:
      POSTGRES_DB: "db_for_proj"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: